services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "14/02Luc"
      MYSQL_DATABASE: "projeto"
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      # Adicionado usuário e senha para o ping funcionar
      test: ["CMD", "sh", "-c", "mysqladmin ping -h localhost -u root -p$$MYSQL_ROOT_PASSWORD"]
      timeout: 20s
      retries: 10

  app:
    build: .
    restart: unless-stopped
    depends_on:
      # Alterado para exigir que o banco esteja "saudável"
      db:
        condition: service_healthy
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      DB_NAME: projeto
      DB_USER: root
      DB_PASS: "14/02Luc"
      DB_HOST: db
      DB_PORT: 3306
      SESSION_SECRET: algumsegredo
      AUTO_SYNC: "1"
      COOKIE_SECURE: "0"
    ports:
      - "3001:3000"

volumes:
  db_data: